<a href="https://colab.research.google.com/github/CyprianSwiech/data-science-bootcamp/blob/main/02_algebra_liniowa.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
import numpy as np

In [4]:
v1 = np.array([-1, 4])
v1

array([-1,  4])

In [5]:
np.linalg.norm(v1)

4.123105625617661

In [6]:
v2 = np.array([-10, 10, 13])
np.linalg.norm(v2)

19.209372712298546

In [7]:
p = np.array([3, 0])
q = np.array([0, 4])
np.linalg.norm(p - q)

5.0

In [8]:
p = np.array([3, 0, 1])
q = np.array([0, 4, 2])

np.linalg.norm(p - q)

5.0990195135927845

In [11]:
X = np.array([[5, 3], [3, 9]])
Y = np.array([[1], [-1]])
print(X, 2*'\n', Y)

[[5 3]
 [3 9]] 

 [[ 1]
 [-1]]


In [15]:
Z = np.dot(X, Y)
Z

array([[ 2],
       [-6]])

In [13]:
Z.shape

(2, 1)

In [16]:
X = np.array([[2, -1, 3], [3, 1, 0]])
Y = np.array([[2, 1, -1], [0, -1, 2], [3, 2, 0]])
print(X, '\n')
print(Y)

[[ 2 -1  3]
 [ 3  1  0]] 

[[ 2  1 -1]
 [ 0 -1  2]
 [ 3  2  0]]


In [17]:
Z = np.dot(X, Y)

In [18]:
Z

array([[13,  9, -4],
       [ 6,  2, -1]])

In [19]:
A = np.array([[2, 4], [-1, 3]])
A

array([[ 2,  4],
       [-1,  3]])

In [21]:
round(np.linalg.det(A))

10

In [22]:
A = np.array([[2, 4], [-1, 3]])
np.trace(A)

5

In [23]:
np.eye(5, dtype='int')

array([[1, 0, 0, 0, 0],
       [0, 1, 0, 0, 0],
       [0, 0, 1, 0, 0],
       [0, 0, 0, 1, 0],
       [0, 0, 0, 0, 1]])

In [24]:
np.eye(3)

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [25]:
A

array([[ 2,  4],
       [-1,  3]])

In [26]:
B = np.linalg.inv(A)

In [27]:
B

array([[ 0.3, -0.4],
       [ 0.1,  0.2]])

In [28]:
np.dot(A, B)

array([[1.00000000e+00, 0.00000000e+00],
       [2.77555756e-17, 1.00000000e+00]])

In [29]:
np.set_printoptions(precision=4, suppress=True)

In [30]:
np.dot(A, B)

array([[1., 0.],
       [0., 1.]])

In [31]:
np.dot(B, A)

array([[ 1., -0.],
       [ 0.,  1.]])

In [32]:
A

array([[ 2,  4],
       [-1,  3]])

In [33]:
np.transpose(A)

array([[ 2, -1],
       [ 4,  3]])

In [34]:
A.T

array([[ 2, -1],
       [ 4,  3]])

In [35]:
A

array([[ 2,  4],
       [-1,  3]])

In [36]:
A.T

array([[ 2, -1],
       [ 4,  3]])

In [37]:
np.transpose(A)

array([[ 2, -1],
       [ 4,  3]])

In [38]:
A = np.array([[2 ,4], [1, -1]])
print(A)

[[ 2  4]
 [ 1 -1]]


In [39]:
B = np.array([[10], [-1]])
print(B)

[[10]
 [-1]]


In [41]:
A_inv = np.linalg.inv(A)
X = np.dot(A_inv, B)
X

array([[1.],
       [2.]])

In [42]:
X.shape

(2, 1)