<a href="https://colab.research.google.com/github/CyprianSwiech/data-science-bootcamp/blob/main/numpy_intro.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
import numpy as np
np.__version__

'1.26.4'

In [ ]:
print(dir(np))

['ALLOW_THREADS', 'BUFSIZE', 'CLIP', 'DataSource', 'ERR_CALL', 'ERR_DEFAULT', 'ERR_IGNORE', 'ERR_LOG', 'ERR_PRINT', 'ERR_RAISE', 'ERR_WARN', 'FLOATING_POINT_SUPPORT', 'FPE_DIVIDEBYZERO', 'FPE_INVALID', 'FPE_OVERFLOW', 'FPE_UNDERFLOW', 'False_', 'Inf', 'Infinity', 'MAXDIMS', 'MAY_SHARE_BOUNDS', 'MAY_SHARE_EXACT', 'NAN', 'NINF', 'NZERO', 'NaN', 'PINF', 'PZERO', 'RAISE', 'RankWarning', 'SHIFT_DIVIDEBYZERO', 'SHIFT_INVALID', 'SHIFT_OVERFLOW', 'SHIFT_UNDERFLOW', 'ScalarType', 'True_', 'UFUNC_BUFSIZE_DEFAULT', 'UFUNC_PYVALS_NAME', 'WRAP', '_CopyMode', '_NoValue', '_UFUNC_API', '__NUMPY_SETUP__', '__all__', '__builtins__', '__cached__', '__config__', '__deprecated_attrs__', '__dir__', '__doc__', '__expired_functions__', '__file__', '__former_attrs__', '__future_scalars__', '__getattr__', '__loader__', '__name__', '__package__', '__path__', '__spec__', '__version__', '_add_newdoc_ufunc', '_builtins', '_distributor_init', '_financial_names', '_get_promotion_state', '_globals', '_int_extended_ms

In [ ]:
help(np.array)

In [ ]:
x = np.array([1, 3])
x

array([1, 3])

In [ ]:
print(x)

[1 3]


In [ ]:
type(x)

numpy.ndarray

In [ ]:
x.ndim

1

In [ ]:
x.shape

(2,)

In [ ]:
x.size

2

In [ ]:
x.dtype

dtype('int64')

In [ ]:
x.dtype

dtype('int64')

In [ ]:
x = np.array([1.2, 1.1, 3.9])
print(x)

[1.2 1.1 3.9]


In [ ]:
x.dtype

dtype('float64')

In [ ]:
x = np.array([[1, 3], [-3, 8]])
x

array([[ 1,  3],
       [-3,  8]])

In [ ]:
print(x)

[[ 1  3]
 [-3  8]]


In [ ]:
x.ndim

2

In [ ]:
x.shape

(2, 2)

In [ ]:
x = np.array([[1, 8, 10, 2], [2, 9, 11, 2]])
print(x)

[[ 1  8 10  2]
 [ 2  9 11  2]]


In [ ]:
x.ndim

2

In [ ]:
x.shape

(2, 4)

In [ ]:
x = np.array(
    [[[1, 3, 1],
      [5, 9, 10]],

     [[4, 1, 6],
      [10, 12, 2]],

     [[4, 21, 5],
      [11, 5, 22]]
     ])
x

array([[[ 1,  3,  1],
        [ 5,  9, 10]],

       [[ 4,  1,  6],
        [10, 12,  2]],

       [[ 4, 21,  5],
        [11,  5, 22]]])

In [ ]:
print(x)

[[[ 1  3  1]
  [ 5  9 10]]

 [[ 4  1  6]
  [10 12  2]]

 [[ 4 21  5]
  [11  5 22]]]


In [ ]:
x.ndim

3

In [ ]:
x.shape

(3, 2, 3)

In [ ]:
a = np.array([1, 2])
a.dtype

dtype('int64')

In [ ]:
a = np.array([1.2, 1.1, 3.2, 2.1])
a.dtype

dtype('float64')

In [ ]:
a = np.array([1, 3, 5], dtype=float)
a.dtype

dtype('float64')

In [ ]:
print(a)

[1. 3. 5.]


In [ ]:
a = np.array([1, 3, 5], dtype=complex)
a.dtype

dtype('complex128')

In [ ]:
a

array([1.+0.j, 3.+0.j, 5.+0.j])

In [ ]:
a = np.array([1.2, 3.5, 5.8], dtype=int)
a.dtype

dtype('int64')

In [ ]:
a

array([1, 3, 5])

In [ ]:
print(a)

[1 3 5]


In [ ]:
a = np.array([True, False])
a.dtype

dtype('bool')

In [ ]:
print(a)

[ True False]


In [ ]:
a = np.array([1, 3, 5], dtype=np.int8)
a.dtype

dtype('int8')

In [ ]:
a

array([1, 3, 5], dtype=int8)

In [ ]:
print(a)

[1 3 5]


In [ ]:
a = np.array([20, 250, 120], dtype=np.uint8)
a.dtype

dtype('uint8')

In [ ]:
print(a)

[ 20 250 120]


In [ ]:
a

array([ 20, 250, 120], dtype=uint8)

In [ ]:
np.zeros(shape=(4, 10))

array([[0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.]])

In [ ]:
np.zeros(shape=(4, 10), dtype='int')

array([[0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0, 0]])

In [ ]:
np.ones(shape=(5, 5))

array([[1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.]])

In [ ]:
np.ones(shape=(5, 5), dtype="int")

array([[1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1]])

In [ ]:
np.full(shape=(3, 3), fill_value=4, dtype='int')

array([[4, 4, 4],
       [4, 4, 4],
       [4, 4, 4]])

In [ ]:
np.arange(10)

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [ ]:
np.arange(start=10, stop=100, step=10)

array([10, 20, 30, 40, 50, 60, 70, 80, 90])

In [ ]:
np.arange(start=100, stop=10, step=-10)

array([100,  90,  80,  70,  60,  50,  40,  30,  20])

In [ ]:
np.arange(start=0, stop=1, step=0.05)

array([0.  , 0.05, 0.1 , 0.15, 0.2 , 0.25, 0.3 , 0.35, 0.4 , 0.45, 0.5 ,
       0.55, 0.6 , 0.65, 0.7 , 0.75, 0.8 , 0.85, 0.9 , 0.95])

In [ ]:
np.linspace(start=0, stop=1, num=10)

array([0.        , 0.11111111, 0.22222222, 0.33333333, 0.44444444,
       0.55555556, 0.66666667, 0.77777778, 0.88888889, 1.        ])

In [ ]:
A = np.arange(15)
A

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14])

In [ ]:
A.reshape((3, 5))

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14]])

In [ ]:
A.reshape((3, -1))

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14]])

In [ ]:
A.reshape((-1, 3))

array([[ 0,  1,  2],
       [ 3,  4,  5],
       [ 6,  7,  8],
       [ 9, 10, 11],
       [12, 13, 14]])

In [ ]:
A = np.array([1, 4, -2, 3])
B = np.array([2, -5, 6, 1])
print(A)
print(B)

[ 1  4 -2  3]
[ 2 -5  6  1]


In [ ]:
np.add(A, B)

array([ 3, -1,  4,  4])

In [ ]:
np.subtract(A, B)

array([-1,  9, -8,  2])

In [ ]:
np.multiply(A, B)

array([  2, -20, -12,   3])

In [ ]:
np.divide(A, B)

array([ 0.5       , -0.8       , -0.33333333,  3.        ])

In [ ]:
A + 10

array([11, 14,  8, 13])

In [ ]:
A * 4

array([ 4, 16, -8, 12])

In [ ]:
A + B*4

array([  9, -16,  22,   7])

In [ ]:
X = np.array([[6, 0], [9, 12]])
Y = np.array([[3, 5], [2, 0]])
print(X, '\n')
print(Y)

[[ 6  0]
 [ 9 12]] 

[[3 5]
 [2 0]]


In [ ]:
X * Y

array([[18,  0],
       [18,  0]])

In [ ]:
np.dot(X, Y)

array([[18, 30],
       [51, 45]])

In [ ]:
X.dot(Y)

array([[18, 30],
       [51, 45]])

In [ ]:
Y.dot(X)

array([[63, 60],
       [12,  0]])

In [ ]:
X @ Y

array([[18, 30],
       [51, 45]])

In [ ]:
Y @ X

array([[63, 60],
       [12,  0]])

In [ ]:
np.random.randn()

1.0578521576561524

In [ ]:
np.random.randn()

-0.3756486038362575

In [ ]:
np.random.randn(10)

array([ 0.13319631,  0.88943494, -0.05138628,  0.66550047,  0.8544452 ,
       -1.25270843, -1.21110619,  0.18905135, -0.24187271,  0.05943551])

In [ ]:
np.random.randn(10, 4)

array([[-1.27832703, -0.94546842, -0.80918949, -0.83202691],
       [-1.13252673,  0.59229141,  0.1784423 ,  0.21221828],
       [ 0.37531544,  0.71637227, -2.18648302, -1.40713564],
       [-1.50903926,  1.08538275,  0.9536115 ,  1.10117954],
       [ 0.39648304,  2.04453525, -0.39745863,  0.14182575],
       [-0.8863935 , -0.91170849,  0.68357357, -0.64971459],
       [-1.22319553, -0.04195547,  0.49449862, -0.32679798],
       [ 0.27323241,  0.03150446,  0.18512806, -0.64823414],
       [-1.21194624, -1.00776769,  1.17540861,  1.45009514],
       [ 0.109051  , -1.09707195,  1.59985434,  0.29437044]])

In [ ]:
np.random.rand()

0.8641578323582217

In [ ]:
np.random.rand(10, 2)

array([[0.28671629, 0.96440578],
       [0.20206347, 0.48345168],
       [0.37649142, 0.45762082],
       [0.59785918, 0.21033576],
       [0.8775062 , 0.45144458],
       [0.7818648 , 0.96414073],
       [0.39044137, 0.49127941],
       [0.72560352, 0.48409319],
       [0.56565482, 0.43024881],
       [0.51608809, 0.62988894]])

In [ ]:
np.random.randint(10)

4

In [ ]:
np.random.randint(low=10, high=100, size=20)

array([78, 72, 25, 88, 92, 75, 96, 80, 33, 40, 88, 60, 13, 94, 15, 58, 30,
       44, 65, 67])

In [ ]:
np.random.choice([1, 9, 10, 2, 5])

2

In [ ]:
np.random.choice(['python', 'java', 'sql'])

'sql'

In [ ]:
data = np.arange(10)
data

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [ ]:
np.random.shuffle(data)

In [ ]:
data

array([2, 8, 5, 9, 0, 3, 1, 7, 4, 6])

In [ ]:
data2 = np.arange(start=10, stop=100, step=10)

In [ ]:
np.random.shuffle(data2)

In [ ]:
data

array([2, 8, 5, 9, 0, 3, 1, 7, 4, 6])

In [ ]:
data2

array([50, 10, 30, 20, 90, 70, 80, 60, 40])

In [ ]:
import numpy

In [ ]:
numpy.exp(1)

2.718281828459045

In [ ]:
numpy.sqrt(9)

3.0

In [ ]:
 numpy.sqrt(90)

9.486832980505138

In [ ]:
numpy.any([1, 3, 5, 0])

True

In [ ]:
numpy.any([0, 0, 0, 0])

False

In [ ]:
numpy.all([1, 3, 5])

True

In [ ]:
A = numpy.random.rand(5)
A

array([0.40205826, 0.69576249, 0.31524173, 0.98711552, 0.01199762])

In [ ]:
numpy.argmax(A)

3

In [ ]:
A[numpy.argmax(A)]

0.9871155155804003

In [ ]:
numpy.argmin(A)

4

In [ ]:
A[numpy.argmin(A)]

0.011997624695659237

In [ ]:
numpy.argsort(A)

array([4, 2, 0, 1, 3])

In [ ]:
numpy.max(A)

0.9871155155804003

In [ ]:
numpy.min(A)

0.011997624695659237

In [ ]:
numpy.mean(A)

0.4824351237911208

In [ ]:
numpy.median(A)

0.40205826144317347

In [ ]:
numpy.std(A)

0.33344756006140774

In [ ]:
numpy.argsort(A)

array([4, 2, 0, 1, 3])

In [ ]:
A = numpy.arange(20)
A

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19])

In [ ]:
A[2]

2

In [ ]:
A[:5]

array([0, 1, 2, 3, 4])

In [ ]:
A[10:]

array([10, 11, 12, 13, 14, 15, 16, 17, 18, 19])

In [ ]:
A[10:15]

array([10, 11, 12, 13, 14])

In [ ]:
A[-1]

19

In [ ]:
A[-2]

18

In [ ]:
A = A.reshape(4, 5)
A

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19]])

In [ ]:
A[1:3, 1:4]

array([[ 6,  7,  8],
       [11, 12, 13]])

In [ ]:
A[0]

array([0, 1, 2, 3, 4])

In [ ]:
A[1]

array([5, 6, 7, 8, 9])

In [ ]:
A[-1]

array([15, 16, 17, 18, 19])

In [ ]:
A[0, 2]

2

In [ ]:
A[:, -1]

array([ 4,  9, 14, 19])

In [ ]:
A[:, 1]

array([ 1,  6, 11, 16])

In [ ]:
A[1, 3]

8

In [ ]:
A[1, 2]

7

In [ ]:
A[1, 2] = 14
A

array([[ 0,  1,  2,  3,  4],
       [ 5,  6, 14,  8,  9],
       [10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19]])

In [ ]:
A[-1, -1] = 222
A

array([[  0,   1,   2,   3,   4],
       [  5,   6,  14,   8,   9],
       [ 10,  11,  12,  13,  14],
       [ 15,  16,  17,  18, 222]])

In [ ]:
A[2, 1] = 111

In [ ]:
print(A)

[[  0   1   2   3   4]
 [  5   6  14   8   9]
 [ 10 111  12  13  14]
 [ 15  16  17  18 222]]


In [ ]:
A[3, 3] = 3

In [ ]:
A

array([[  0,   1,   2,   3,   4],
       [  5,   6,  14,   8,   9],
       [ 10, 111,  12,  13,  14],
       [ 15,  16,  17,   3, 222]])

In [ ]:
import numpy as np
np.__version__

'1.26.4'

In [ ]:
x = np.array([1, 3])
x

array([1, 3])

In [ ]:
print(x)

[1 3]


In [ ]:
type(x)

numpy.ndarray

In [ ]:
x.ndim

1

In [ ]:
y = np.array([2, 4, 6])
print(y)

[2 4 6]


In [ ]:
y.shape

(3,)

In [ ]:
y.size

3

In [ ]:
y.ndim

1

In [ ]:
y.dtype

dtype('int64')

In [ ]:
x = np.array([1.3, 1.2, 9.1])
print(x)

[1.3 1.2 9.1]


In [ ]:
x.dtype

dtype('float64')

In [ ]:
x = np.array([[1, 4], [8, -9]])
x

array([[ 1,  4],
       [ 8, -9]])

In [ ]:
x.size

4

In [ ]:
x.shape

(2, 2)

In [ ]:
x.ndim

2

In [ ]:
x.dtype

dtype('int64')

In [ ]:
x = np.array([[1, 2, 3], [5, 1, -10]])
print(x)

[[  1   2   3]
 [  5   1 -10]]


In [ ]:
x.ndim

2

In [ ]:
x.shape

(2, 3)

In [ ]:
x = np.array(
    [[[1, 6, 3],
      [9, -1, -3]],

     [[1, 0, 0],
      [2, 4, 1]],

     [[9, 12, 3],
      [11, 0, 44]]]
)
print(x)

[[[ 1  6  3]
  [ 9 -1 -3]]

 [[ 1  0  0]
  [ 2  4  1]]

 [[ 9 12  3]
  [11  0 44]]]


In [ ]:
x.ndim

3

In [ ]:
x.shape

(3, 2, 3)

In [ ]:
x.size

18

In [ ]:
x.shape

(3, 2, 3)

In [ ]:
x.ndim

3

In [ ]:
x = np.array([1, 2, 3])
x.dtype

dtype('int64')

In [ ]:
A = np.array([1.0, 2.3, 3.9], dtype='int')
A

array([1, 2, 3])

In [ ]:
A = np.array([1, 2, 3], dtype='complex')
A.dtype
A

array([1.+0.j, 2.+0.j, 3.+0.j])

In [ ]:
A.dtype

dtype('complex128')

In [ ]:
A = np.array([24, 250, 13], dtype='uint8')
A.dtype

dtype('uint8')

In [ ]:
a = np.zeros(shape=(2, 4, 10))
print(a)

[[[0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
  [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
  [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
  [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]]

 [[0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
  [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
  [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
  [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]]]


In [ ]:
A = np.zeros(shape=(4, 10), dtype='int')

In [ ]:
A

array([[0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0, 0]])

In [ ]:
a = np.ones(shape=(5, 5))
a

array([[1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.]])

In [ ]:
A = np.ones(shape=(5, 5), dtype='int')

In [ ]:
A

array([[1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1]])

In [ ]:
A = np.full(shape=(3, 3), fill_value=4, dtype='int')

In [ ]:
A

array([[4, 4, 4],
       [4, 4, 4],
       [4, 4, 4]])

In [ ]:
A = np.array([True, False])

In [ ]:
A.dtype

dtype('bool')

In [ ]:
A = np.arange(10)
print(A)

[0 1 2 3 4 5 6 7 8 9]


In [ ]:
A = np.arange(5, 10)
A

array([5, 6, 7, 8, 9])

In [ ]:
A = np.arange(start=10, stop=100, step=10)
A

array([10, 20, 30, 40, 50, 60, 70, 80, 90])

In [ ]:
A = np.arange(start=100, stop=10, step=-10)
A

array([100,  90,  80,  70,  60,  50,  40,  30,  20])

In [ ]:
np.arange(start=0, stop=1, step=0.05)

array([0.  , 0.05, 0.1 , 0.15, 0.2 , 0.25, 0.3 , 0.35, 0.4 , 0.45, 0.5 ,
       0.55, 0.6 , 0.65, 0.7 , 0.75, 0.8 , 0.85, 0.9 , 0.95])

In [ ]:
np.linspace(start=0, stop=1, num=11)

array([0. , 0.1, 0.2, 0.3, 0.4, 0.5, 0.6, 0.7, 0.8, 0.9, 1. ])

In [ ]:
A = np.arange(15)
A

1

In [ ]:
A.reshape((3, 5))

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14]])

1

In [ ]:
A.reshape((3, -1))

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14]])

In [ ]:
A.reshape((-1, 3))

array([[ 0,  1,  2],
       [ 3,  4,  5],
       [ 6,  7,  8],
       [ 9, 10, 11],
       [12, 13, 14]])

In [ ]:
A.size

15

In [ ]:
A.reshape((15, 1))

array([[ 0],
       [ 1],
       [ 2],
       [ 3],
       [ 4],
       [ 5],
       [ 6],
       [ 7],
       [ 8],
       [ 9],
       [10],
       [11],
       [12],
       [13],
       [14]])

In [ ]:
A.reshape

In [ ]:
import numpy as np

In [ ]:
A = np.array([1, 6, 2, 9])
B = np.array([5, 10, 2, 7])

In [ ]:
A + B

array([ 6, 16,  4, 16])

In [ ]:
A - B

array([-4, -4,  0,  2])

In [ ]:
A * B

array([ 5, 60,  4, 63])

In [ ]:
A / B

array([0.2       , 0.6       , 1.        , 1.28571429])

In [ ]:
A + 3

array([ 4,  9,  5, 12])

In [ ]:
A * 2

array([ 2, 12,  4, 18])

In [ ]:
A + 3*B

array([16, 36,  8, 30])

In [ ]:
np.add(A, B)

array([ 6, 16,  4, 16])

In [ ]:
np.subtract(A, B)

array([-4, -4,  0,  2])

In [ ]:
np.divide(A, B)

array([0.2       , 0.6       , 1.        , 1.28571429])

In [ ]:
np.multiply(A, B)

array([ 5, 60,  4, 63])

In [ ]:
X = np.array([[0, 10], [-5, 2]])
Y = np.array([[5, 10], [23, 4]])

In [ ]:
print(X, '\n')
print(Y)

[[ 0 10]
 [-5  2]] 

[[ 5 10]
 [23  4]]


In [ ]:
np.dot(X, Y)

array([[230,  40],
       [ 21, -42]])

In [ ]:
X.dot(Y)

array([[230,  40],
       [ 21, -42]])

In [ ]:
Y.dot(X)

array([[-50,  70],
       [-20, 238]])

In [ ]:
X @ Y

array([[230,  40],
       [ 21, -42]])

In [ ]:
Y @ X

array([[-50,  70],
       [-20, 238]])

In [ ]:
import numpy as np

In [ ]:
np.random.seed(0)

In [ ]:
np.random.randn()

1.764052345967664

In [ ]:
np.random.randn()

0.4001572083672233

In [ ]:
np.random.randn(10)

array([ 0.97873798,  2.2408932 ,  1.86755799, -0.97727788,  0.95008842,
       -0.15135721, -0.10321885,  0.4105985 ,  0.14404357,  1.45427351])

In [ ]:
np.random.randn(10, 4)

array([[ 0.76103773,  0.12167502,  0.44386323,  0.33367433],
       [ 1.49407907, -0.20515826,  0.3130677 , -0.85409574],
       [-2.55298982,  0.6536186 ,  0.8644362 , -0.74216502],
       [ 2.26975462, -1.45436567,  0.04575852, -0.18718385],
       [ 1.53277921,  1.46935877,  0.15494743,  0.37816252],
       [-0.88778575, -1.98079647, -0.34791215,  0.15634897],
       [ 1.23029068,  1.20237985, -0.38732682, -0.30230275],
       [-1.04855297, -1.42001794, -1.70627019,  1.9507754 ],
       [-0.50965218, -0.4380743 , -1.25279536,  0.77749036],
       [-1.61389785, -0.21274028, -0.89546656,  0.3869025 ]])

In [ ]:
np.random.rand()

0.1965823616800535

In [ ]:
np.random.rand(10)

array([0.36872517, 0.82099323, 0.09710128, 0.83794491, 0.09609841,
       0.97645947, 0.4686512 , 0.97676109, 0.60484552, 0.73926358])

In [ ]:
np.random.rand(10, 2)

array([[0.03918779, 0.28280696],
       [0.12019656, 0.2961402 ],
       [0.11872772, 0.31798318],
       [0.41426299, 0.0641475 ],
       [0.69247212, 0.56660145],
       [0.26538949, 0.52324805],
       [0.09394051, 0.5759465 ],
       [0.9292962 , 0.31856895],
       [0.66741038, 0.13179786],
       [0.7163272 , 0.28940609]])

In [ ]:
np.random.randint(10)

3

In [ ]:
np.random.randint(20)

14

In [ ]:
np.random.randint(low=10, high=100)

52

In [ ]:
np.random.randint(low=200, high=300, size=20)

array([256, 260, 277, 230, 224, 202, 203, 294, 298, 213, 240, 272, 219,
       295, 272, 226, 266, 252, 267, 261])

In [ ]:
np.random.choice([1, 2, 4, 5, 7, 10, 2])

5

In [ ]:
np.random.choice(['python', 'sql', 'java'])

'python'

In [ ]:
data = np.arange(10)
data

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [ ]:
np.random.shuffle(data)
data

array([2, 4, 3, 9, 1, 5, 7, 0, 8, 6])

In [ ]:
np.exp(1)

2.718281828459045

In [ ]:
np.sqrt(9)

3.0

In [ ]:
np.sqrt(16)

4.0

In [ ]:
np.all([2, 4, 5, 1, 0])

False

In [ ]:
np.any([1, 0, 2, 5, 0])

True

In [ ]:
np.any([0, 0, 0, 0])

False

In [ ]:
bool(0)

False

In [ ]:
bool(1)

True

In [ ]:
A = np.random.rand(5)

In [ ]:
A

array([0.50132438, 0.95608363, 0.6439902 , 0.42385505, 0.60639321])

In [ ]:
np.argmax(A)

1

In [ ]:
A[np.argmax(A)]

0.9560836347232239

In [ ]:
np.argmin(A)

3

In [ ]:
A[np.argmin(A)]

0.4238550485581797

In [ ]:
np.argsort(A)

array([3, 0, 4, 2, 1])

In [ ]:
np.argsort(A)

array([3, 0, 4, 2, 1])

In [ ]:
np.max(A)

0.9560836347232239

In [ ]:
np.min(A)

0.4238550485581797

In [ ]:
np.mean(A)

0.6263292957131336

In [ ]:
np.std(A)

0.18224671639823387

In [ ]:
np.median(A)

0.6063932141279244

In [ ]:
np.max(A)

0.9560836347232239

In [ ]:
np.min(A)

0.4238550485581797

In [ ]:
np.std(A)

0.18224671639823387

In [ ]:
np.median(A)

0.6063932141279244

In [ ]:
import numpy as np

In [ ]:
A = np.arange(20)

In [ ]:
A

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19])

In [ ]:
np.argmin(A)

0

In [ ]:
np.min(A)

0

In [ ]:
np.argmax(A)

19

In [ ]:
np.max(A)

19

In [ ]:
np.std(A)

5.766281297335398

In [ ]:
np.mean(A)

9.5

In [ ]:
np.median(A)

9.5

In [ ]:
A[2]

2

In [ ]:
A[0]

0

In [ ]:
A

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19])

In [ ]:
A[0]

0

In [ ]:
A[7]

7

In [ ]:
A[3:10]

array([3, 4, 5, 6, 7, 8, 9])

In [ ]:
A[2:]

array([ 2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17, 18,
       19])

In [ ]:
A[:12]

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11])

In [ ]:
A[-1]

19

In [ ]:
A[-2]

18

In [ ]:
np.size(A)

20

In [ ]:
A = A.reshape(4, -1)

In [ ]:
A

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19]])

In [ ]:
A[0]

array([0, 1, 2, 3, 4])

In [ ]:
A[:, 0]

array([ 0,  5, 10, 15])

In [ ]:
A[1, 3]

8

In [ ]:
A[2, 2] = 24
A

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 24, 13, 14],
       [15, 16, 17, 18, 19]])

In [ ]:
A[1:3, 1:4]

array([[ 6,  7,  8],
       [11, 24, 13]])

In [ ]:
A[-1, -1]

19

In [ ]:
A[2, 0]

10

In [ ]:
A[0:2, 0:3]

array([[0, 1, 2],
       [5, 6, 7]])

In [ ]:
A[:, -1]

array([ 4,  9, 14, 19])

In [ ]:
A[:, 2]

array([ 2,  7, 24, 17])

In [ ]:
A[2]

array([10, 11, 24, 13, 14])

In [ ]:
import numpy as np

In [ ]:
A = np.arange(20)
A = A.reshape(4, 5)

In [ ]:
A

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19]])

In [ ]:
for row in A:
  print(row)

[0 1 2 3 4]
[5 6 7 8 9]
[10 11 12 13 14]
[15 16 17 18 19]


In [ ]:
for row in A:
  print(row[0])

0
5
10
15


In [ ]:
for row in A:
  print(row[:3])

[0 1 2]
[5 6 7]
[10 11 12]
[15 16 17]


In [ ]:
for item in A.flat:
  print(item)

0
1
2
3
4
5
6
7
8
9
10
11
12
13
14
15
16
17
18
19


In [2]:
A

NameError: name 'A' is not defined

In [ ]:
A.shape

(4, 5)

In [ ]:
A.T

array([[ 0,  5, 10, 15],
       [ 1,  6, 11, 16],
       [ 2,  7, 12, 17],
       [ 3,  8, 13, 18],
       [ 4,  9, 14, 19]])

In [ ]:
A.ravel()

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19])

In [1]:
A.reshape(5, 4)

NameError: name 'A' is not defined

In [3]:
import numpy as np

In [4]:
A = np.arange(20)

In [5]:
A

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19])

In [8]:
A = A.reshape(4, 5)

In [9]:
A

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19]])

In [11]:
for row in A:
  print(row)

[0 1 2 3 4]
[5 6 7 8 9]
[10 11 12 13 14]
[15 16 17 18 19]


In [12]:
for row in A:
  print(row[0])

0
5
10
15


In [13]:
for row in A:
  print(row[1:4])

[1 2 3]
[6 7 8]
[11 12 13]
[16 17 18]


In [14]:
for row in A:
  print(row[:3])

[0 1 2]
[5 6 7]
[10 11 12]
[15 16 17]


In [15]:
A[1, 2] = 14
A

array([[ 0,  1,  2,  3,  4],
       [ 5,  6, 14,  8,  9],
       [10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19]])

In [17]:
A = A.reshape(5, 4)
A

array([[ 0,  1,  2,  3],
       [ 4,  5,  6, 14],
       [ 8,  9, 10, 11],
       [12, 13, 14, 15],
       [16, 17, 18, 19]])

In [18]:
A.shape

(5, 4)

In [22]:
A = np.arange(20)

In [23]:
A = A.reshape(4, -1)

In [25]:
A.ravel()

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19])

In [26]:
A

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19]])

In [27]:
A.T

array([[ 0,  5, 10, 15],
       [ 1,  6, 11, 16],
       [ 2,  7, 12, 17],
       [ 3,  8, 13, 18],
       [ 4,  9, 14, 19]])

In [32]:
A = np.arange(start=-10, stop=10, step=0.5)
A

array([-10. ,  -9.5,  -9. ,  -8.5,  -8. ,  -7.5,  -7. ,  -6.5,  -6. ,
        -5.5,  -5. ,  -4.5,  -4. ,  -3.5,  -3. ,  -2.5,  -2. ,  -1.5,
        -1. ,  -0.5,   0. ,   0.5,   1. ,   1.5,   2. ,   2.5,   3. ,
         3.5,   4. ,   4.5,   5. ,   5.5,   6. ,   6.5,   7. ,   7.5,
         8. ,   8.5,   9. ,   9.5])

In [33]:
A = A.reshape(10, -1)

In [34]:
A

array([[-10. ,  -9.5,  -9. ,  -8.5],
       [ -8. ,  -7.5,  -7. ,  -6.5],
       [ -6. ,  -5.5,  -5. ,  -4.5],
       [ -4. ,  -3.5,  -3. ,  -2.5],
       [ -2. ,  -1.5,  -1. ,  -0.5],
       [  0. ,   0.5,   1. ,   1.5],
       [  2. ,   2.5,   3. ,   3.5],
       [  4. ,   4.5,   5. ,   5.5],
       [  6. ,   6.5,   7. ,   7.5],
       [  8. ,   8.5,   9. ,   9.5]])

In [35]:
A > 0

array([[False, False, False, False],
       [False, False, False, False],
       [False, False, False, False],
       [False, False, False, False],
       [False, False, False, False],
       [False,  True,  True,  True],
       [ True,  True,  True,  True],
       [ True,  True,  True,  True],
       [ True,  True,  True,  True],
       [ True,  True,  True,  True]])

In [36]:
A[A > 0]

array([0.5, 1. , 1.5, 2. , 2.5, 3. , 3.5, 4. , 4.5, 5. , 5.5, 6. , 6.5,
       7. , 7.5, 8. , 8.5, 9. , 9.5])

In [37]:
np.bitwise_and(A > -5, A < 5)

array([[False, False, False, False],
       [False, False, False, False],
       [False, False, False,  True],
       [ True,  True,  True,  True],
       [ True,  True,  True,  True],
       [ True,  True,  True,  True],
       [ True,  True,  True,  True],
       [ True,  True, False, False],
       [False, False, False, False],
       [False, False, False, False]])

In [38]:
A[np.bitwise_and(A > -5, A < 5)]

array([-4.5, -4. , -3.5, -3. , -2.5, -2. , -1.5, -1. , -0.5,  0. ,  0.5,
        1. ,  1.5,  2. ,  2.5,  3. ,  3.5,  4. ,  4.5])

In [39]:
np.bitwise_or(A > 5, A < -5)

array([[ True,  True,  True,  True],
       [ True,  True,  True,  True],
       [ True,  True, False, False],
       [False, False, False, False],
       [False, False, False, False],
       [False, False, False, False],
       [False, False, False, False],
       [False, False, False,  True],
       [ True,  True,  True,  True],
       [ True,  True,  True,  True]])